platform :ios, '16.0'
use_frameworks! :linkage => :static

def core_pods
  pod 'private-ownid-core-ios-sdk', :path => '../../internal-ownid-ios-sdk/'
end

def gigya_pods
  pod 'Gigya'
  pod 'GoogleSignIn'
  pod 'private-ownid-gigya-ios-sdk', :path => '../../internal-ownid-ios-sdk/'
  core_pods
end

target 'GigyaDemo' do
  gigya_pods
end

target 'IntegrationDemo' do
  core_pods
end

target 'DirectDemo' do
  core_pods
end

target 'ScreensetsDemo' do
  gigya_pods
end

target 'UIKitInjectionDemo' do
  gigya_pods
end
