platform :ios, '16.0'
use_frameworks!

target 'ScreensetsDemo' do
  pod 'ownid-gigya-ios-sdk'
end

target 'UIKitInjectionDemo' do
  pod 'ownid-gigya-ios-sdk'
end

target 'GigyaDemo' do
  pod 'ownid-gigya-ios-sdk'
end

target 'CustomIntegrationDemo' do
  pod 'ownid-core-ios-sdk'
end

target 'CustomIntegrationCustomViewDemo' do
  pod 'ownid-core-ios-sdk'
end